---
- name: install|configure nfs YUM repository
  yum_repository:
    name: spectrum-scale-nfs-rpms
    description: IBM Spectrum Scale (NFS RPMS)
    baseurl: "{{ scale_install_nfs_repository_rpms }}"
    gpgcheck: false
    state: present
  notify: yum-clean-metadata
  when:
    - ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
    - scale_install_repository_url != 'existing'

- name: install | Configure nfs APT repository
  apt_repository:
    filename: spectrum-scale-nfs-debs
    repo: "deb [trusted=yes] {{ scale_install_nfs_repository_debs }} ./"
    validate_certs: no
    state: present
    update_cache: yes
    codename: IBM Spectrum Scale (NFS debs)
    mode: 0777
  when:
    - ansible_pkg_mgr == 'apt'
    - scale_install_repository_url != 'existing'

- name: install | Add GPFS callhome packages to list
  set_fact:
    scale_install_all_packages: "{{ scale_install_all_packages + [ item ] }}"
  with_items:
    - "{{ scale_nfs_rpms }}"
  when: ansible_distribution == 'Redhat'

- name: install | Add GPFS callhome packages to list
  set_fact:
    scale_install_all_packages: "{{ scale_install_all_packages + [ item ] }}"
  with_items:
    - "{{ scale_nfs_debs }}"
  when: ansible_distribution == 'Ubuntu'


