---
#- name: Create the required groups
- hosts: localhost
  connection: local

  tasks:
  - name: Read all intermediate output from Resource Details
    include_vars:
     dir: vars
     extensions:
     - json

  - name: Pass all inputs related to creating Spectrum Scale cluster to all nodes
    add_host:
     name: "{{ item.fqdn }}"
     groups: scale_node
        #var_scale_version: "{{ scale_version }}"
        #cluster_name: "{{ cluster_name }}"
     scale_storage: "{{ scale_storage }}"
     fqdn: "{{ item.fqdn }}"
     is_protocol_node: "{{ item.is_protocol_node }}"
     is_nfs: "{{ item.is_nfs }}"
     is_smb: "{{ item.is_smb }}"
     is_admin_node: "{{ item.is_admin_node }}"
     os: "{{ item.os }}"
     arch: "{{ item.arch }}"
     ip_address: "{{ item.ip_address }}"
     #callhome_params: "{{ callhome }}"
     protocols: "{{ protocols }}"
     scale_cluster_quorum: "{{ item.is_quorum_node  }}"
     scale_cluster_manager: "{{ item.is_manager_node }}"
    loop: "{{ node_details }}"

