---
- name: Initialize
  set_fact:
   ces_disabled_nodes: []
   export_ips: ""
   server_nodes: ""
   service_list: []

- name: Collect status of ces shared root
  shell:
   cmd: "{{ directory }}mmlsconfig | grep 'cesSharedRoot '"
  register: ces_status
  ignore_errors: true

- name: Configuring cesSharedRoot
  shell:
   cmd: "{{ directory }}mmchconfig cesSharedRoot={{ protocols.mountpoint }}"
  when: ces_status.rc > 0

- name: Prepare server nodes string
  set_fact:
   server_nodes: "{{ server_nodes + ',' + item|string }}"
  with_items:
  - "{{ protocol_nodes_list }}"

- name: Setting server licenses on protocol nodes
  shell:
   cmd: "{{ directory }}mmchlicense server --accept -N {{ server_nodes[1:] }}"
  run_once: true

- name: Collect status of ces nodes
  shell:
   cmd: "{{ directory }}mmces node list|grep {{ item }}"
  register: ces_enable_status
  with_items:
  - "{{ protocol_nodes_list }}"
  run_once: true
  ignore_errors: true

- name: Collect all nodes on which ces is not enabled
  set_fact:
   ces_disabled_nodes: "{{ ces_disabled_nodes + [ item.item ]}}"
  when: item.rc > 0 
  with_items:
  - "{{ ces_enable_status.results }}"

- name: Check if SMB is running
  shell:
   cmd: "{{ directory }}mmces service list|grep SMB"
  register: service_status
  when: ansible_fqdn in protocol_nodes_list
  ignore_errors: true

- name:
  set_fact:
   service_list: "{{ service_list + ['SMB'] }}"
  when: ansible_fqdn in protocol_nodes_list and service_status.rc == 0

- name: Check if NFS is running
  shell:
   cmd: "{{ directory }}mmces service list|grep NFS"
  register: service_status
  when: ansible_fqdn in protocol_nodes_list
  ignore_errors: true

- name:
  set_fact:
   service_list: "{{ service_list + ['NFS'] }}"
  when: ansible_fqdn in protocol_nodes_list and service_status.rc == 0

- debug:
   msg: "{{ service_list }}"

- import_role: 
   name: nfs/node
  when: ces_disabled_nodes|length > 0 and 'NFS' in service_list

- import_role: 
   name: smb/install
  when: ces_disabled_nodes|length > 0 and 'SMB' in service_list

- name: Enabling CES
  shell:
   cmd: "{{ directory }}mmchnode -N {{ item }} --ces-enable"
  with_items:
  - "{{ ces_disabled_nodes }}"
  when: ces_disabled_nodes|length > 0
  run_once: true

- name: Collect status of ces nodes
  shell:
   cmd: "{{ directory }}mmces node list|grep {{ item }}"
  register: ces_enable_status
  with_items:
  - "{{ protocol_nodes_list }}"
  run_once: true

- name: Check CES enabled on all nodes
  assert:
   that:
   -  item.rc == 0
   fail_msg: "CES is not enabled on {{ ansible_hostname }} protocol node"
  with_items:
  - "{{ ces_enable_status.results }}"
  run_once: true

- name: Prepare export ips string
  set_fact:
    export_ips: "{{ export_ips + ',' + item|string }}"
  with_items:
  - "{{ protocols.export_ip_pool }}"

- name: Assign export ips as pool
  shell:
   cmd: "{{ directory }}mmces address add --ces-ip {{ export_ips[1:] }}"
  when: ansible_fqdn in protocol_nodes_list

- name: Rebalance CES IPs
  shell:
   cmd: "{{ directory }}mmces address move --rebalance"
  when: ansible_fqdn in protocol_nodes_list
  run_once: true
