---
- name: Collect status of ces shared root
  shell:
   cmd: "{{ directory }}mmlsconfig | grep 'cesSharedRoot '"
  register: ces_status
  ignore_errors: true

- name: Configuring cesSharedRoot
  shell:
   cmd: "{{ directory }}mmchconfig cesSharedRoot={{ protocols.mountpoint }}"
  when: ces_status.rc > 0

- name: Setting server licenses on protocol nodes
  shell:
   cmd: "{{ directory }}mmchlicense server --accept -N {{ item }}"
  with_items:
  - "{{ protocol_nodes_list }}"
  run_once: true

- name: Enabling CES
  shell:
   cmd: "{{ directory }}mmchnode -N {{ item }} --ces-enable"
  with_items:
  - "{{ protocol_nodes_list }}"
  when: ces_status.rc > 0
  run_once: true

- name: Collect status of ces nodes
  shell:
   cmd: "{{ directory }}mmces node list|grep {{ item }}"
  register: ces_enable_status
  with_items:
  - "{{ protocol_nodes_list }}"
  run_once: true

- name: Check CES enabled on all nodes
  assert:
   that:
   -  item.rc == 0
   fail_msg: "CES is not enabled on {{ ansible_hostname }} protocol node"
  with_items:
  - "{{ ces_enable_status.results }}"
  run_once: true

- name: Assign export ips as pool
  shell:
   cmd: "{{ directory }}mmces address add --ces-ip {{ item }}"
  when: ansible_fqdn in protocol_nodes_list
  with_items:
  - "{{ protocols.export_ip_pool }}"

- name: Rebalance CES IPs
  shell:
   cmd: "{{ directory }}mmces address move --rebalance"
  when: ansible_fqdn in protocol_nodes_list
  run_once: true
