---
# Remote package installation method

- name: install | Stat remote installation package
  stat:
    path: "{{ scale_install_remotepkg_path }}"
  register: scale_install_remotepkg

- name: install | Check remote installation package
  assert:
    that: scale_install_remotepkg.stat.exists
    msg: >-
      Please set the variable 'scale_install_remotepkg_path' to point to the
      remote installation package (accessible on Ansible managed node)!

#
# Optionally, verify package checksum
#
- name: install | Stat checksum file
  stat:
    path: "{{ scale_install_remotepkg_path }}.md5"
  register: scale_install_md5_file

- block:  ## when: scale_install_md5_file.stat.exists
    - name: install | Read checksum from file
      slurp:
        src: "{{ scale_install_remotepkg_path }}.md5"
      register: scale_install_md5_sum

    - name: install | Compare checksums
      vars:
        md5sum: "{{ scale_install_md5_sum.content | b64decode }}"
      assert:
        that: md5sum.strip().split().0 == scale_install_remotepkg.stat.md5
        msg: >-
          Checksums don't match. Please check integritiy of your remote
          installation package!
  when: scale_install_md5_file.stat.exists

#
# Extract installation package
#
- name: install | Stat extracted packages
  stat:
    path: "{{ smb_extracted_path }}"
  register: scale_install_gpfs_rpmdir

- name: install | Make installation package executable
  file:
    path: "{{ scale_install_remotepkg_path }}"
    mode: a+x
  when: not scale_install_gpfs_rpmdir.stat.exists

- name: install | Extract installation package
  command: "{{ scale_install_remotepkg_path + ' --silent' }}"
  args:
    creates:  "{{ smb_extracted_path }}"

- name: install | Stat extracted packages
  stat:
    path: "{{ smb_extracted_path }}"
  register: scale_install_gpfs_rpmdir

- name: install | Check extracted packages
  assert:
    that:
      - scale_install_gpfs_rpmdir.stat.exists
      - scale_install_gpfs_rpmdir.stat.isdir
    msg: >-
      The variable 'scale_version' doesn't seem to match the contents of the
      remote installation package!

- name: install | smb path
  set_fact:
   smb_url: 'smb_rpms/rhel7/'
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '7'

- name: install | smb path
  set_fact:
   smb_url: 'smb_rpms/rhel8/'
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '8'

# Find smb rpms

#
- block:  ## when: host is defined as a protocol node

  - name: install | Find gpfs.smb (gpfs.smb) RPM
    find:
     paths: "{{ smb_extracted_path }}/{{ smb_url }}"
     patterns: gpfs.smb*.rpm
    register: scale_install_gpfs_smb

  - debug:
     msg: "{{ scale_install_gpfs_smb }}"

  - name: install | Check valid GPFS (gpfs.smb) RPM
    assert:
     that: scale_install_gpfs_smb.matched > 0
     msg: "No GPFS smb(gpfs.smb) RPM found {{ smb_extracted_path }}/{{ smb_url }}gpfs.smb*.rpm"


  - debug:
     msg: "{{ scale_install_gpfs_smb }}"

  - name: install | Add GPFS smb RPMs to list
    vars:
     current_rpm: "{{ smb_extracted_path }}/{{ smb_url }}{{ item }}.rpm"
    set_fact:
     scale_install_all_rpms: "{{ scale_install_all_rpms + [ current_rpm ] }}"
    with_items:
    - "{{ scale_install_gpfs_smb.files.0.path | basename | regex_replace('\\.rpm$', '') }}"

