---
- name: Initialize
  set_fact:
   ece_nodes_list: []

- name: Collect all ece nodes
  set_fact:
   ece_nodes_list: "{{ ece_nodes_list + [hostvars[item]['ansible_fqdn']] }}"
  when: hostvars[item]['is_ece_node'] is defined and hostvars[item]['is_ece_node']|bool
  with_items:
   - "{{ ansible_play_hosts }}"
  delegate_to: localhost
  run_once: true

- name: Check if number of ece node is greater than or equal to 4
  assert:
   that:
   - ece_nodes_list|length >= 4
   fail_msg: "Number of ece nodes is less than 4"
  run_once: true

- name: Check if ece node is not protocol node,gui node,nsd node
  assert:
   that:
   - not hostvars[item]['is_protocol_node']|bool
   - not hostvars[item]['scale_cluster_gui']|bool
   - not hostvars[item]['is_nsd_server']|bool
   fail_msg: "ECE node cannot be protocol node,gui node or nsd server"
  with_items:
  - "{{ ece_nodes_list }}"
  run_once: true
  any_errors_fatal: true
