---
scale_install_smb_repository_url: http://9.11.84.162/smb_rpms/
scale_smb_rpms:
- gpfs.smb
scale_rpmversion: "{{ scale_version | regex_replace('^([0-9.]+)\\.([0-9])$', '\\1-\\2') }}"
scale_install_localpkg_tmpdir_path: /tmp
extracted_default_path: "/usr/lpp/mmfs"
gpfs_extracted_path: "{{ extracted_default_path }}/{{ scale_version }}"
